"""Initial schema with users, tags, speeches, game sessions

Revision ID: 59120224f969
Revises: 
Create Date: 2025-12-16 20:18:45.154547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59120224f969'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pg_trgm extension for full-text search
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speeches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('audio_url', sa.String(length=1024), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', name='level', native_enum=False), nullable=False),
    sa.Column('type', sa.Enum('QUESTION', 'ANSWER', name='speechtype', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speeches_level'), 'speeches', ['level'], unique=False)
    op.create_index('ix_speeches_level_type', 'speeches', ['level', 'type'], unique=False)
    op.create_index('ix_speeches_text_fts', 'speeches', ['text'], unique=False, postgresql_using='gin', postgresql_ops={'text': 'gin_trgm_ops'})
    op.create_table('tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_category'), 'tags', ['category'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.Enum('EMAIL', 'GOOGLE', 'APPLE', 'FACEBOOK', name='authprovider', native_enum=False), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_auth_provider_id', 'users', ['auth_provider', 'auth_provider_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('game_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('LISTEN_ONLY', 'LISTEN_AND_REPEAT', name='gamemode', native_enum=False), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('selected_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_speeches', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('avg_pronunciation_score', sa.Float(), nullable=True),
    sa.Column('avg_accuracy_score', sa.Float(), nullable=True),
    sa.Column('avg_fluency_score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_sessions_mode_level', 'game_sessions', ['mode', 'level'], unique=False)
    op.create_index('ix_game_sessions_user_completed', 'game_sessions', ['user_id', 'completed_at'], unique=False)
    op.create_index(op.f('ix_game_sessions_user_id'), 'game_sessions', ['user_id'], unique=False)
    op.create_table('speech_tags',
    sa.Column('speech_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['speech_id'], ['speeches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('speech_id', 'tag_id')
    )
    op.create_table('game_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('speech_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('user_response', sa.Enum('CORRECT', 'INCORRECT', 'SKIPPED', name='userresponse', native_enum=False), nullable=False),
    sa.Column('recognized_text', sa.Text(), nullable=True),
    sa.Column('pronunciation_score', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('word_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speech_id'], ['speeches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_results_session_id'), 'game_results', ['session_id'], unique=False)
    op.create_index('ix_game_results_session_sequence', 'game_results', ['session_id', 'sequence_number'], unique=False)
    op.create_index(op.f('ix_game_results_speech_id'), 'game_results', ['speech_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_results_speech_id'), table_name='game_results')
    op.drop_index('ix_game_results_session_sequence', table_name='game_results')
    op.drop_index(op.f('ix_game_results_session_id'), table_name='game_results')
    op.drop_table('game_results')
    op.drop_table('speech_tags')
    op.drop_index(op.f('ix_game_sessions_user_id'), table_name='game_sessions')
    op.drop_index('ix_game_sessions_user_completed', table_name='game_sessions')
    op.drop_index('ix_game_sessions_mode_level', table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_auth_provider_id', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_category'), table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_speeches_text_fts', table_name='speeches', postgresql_using='gin', postgresql_ops={'text': 'gin_trgm_ops'})
    op.drop_index('ix_speeches_level_type', table_name='speeches')
    op.drop_index(op.f('ix_speeches_level'), table_name='speeches')
    op.drop_table('speeches')
    # ### end Alembic commands ###
