// Mocks generated by Mockito 5.4.4 from annotations
// in english_learning_app/test/unit/repositories/game_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:connectivity_plus/connectivity_plus.dart' as _i10;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i11;
import 'package:english_learning_app/core/constants/enums.dart' as _i5;
import 'package:english_learning_app/data/datasources/local/game_local_datasource.dart'
    as _i3;
import 'package:english_learning_app/data/datasources/remote/game_remote_datasource.dart'
    as _i8;
import 'package:english_learning_app/data/models/game_session_model.dart'
    as _i2;
import 'package:english_learning_app/data/models/speech_model.dart' as _i7;
import 'package:english_learning_app/data/models/tag_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGameSessionModel_0 extends _i1.SmartFake
    implements _i2.GameSessionModel {
  _FakeGameSessionModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GameLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameLocalDataSource extends _i1.Mock
    implements _i3.GameLocalDataSource {
  MockGameLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GameSessionModel> saveSession(_i2.GameSessionModel? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSession,
          [session],
        ),
        returnValue:
            _i4.Future<_i2.GameSessionModel>.value(_FakeGameSessionModel_0(
          this,
          Invocation.method(
            #saveSession,
            [session],
          ),
        )),
      ) as _i4.Future<_i2.GameSessionModel>);

  @override
  _i4.Future<List<_i2.GameSessionModel>> getSessions({
    String? userId,
    _i5.GameMode? mode,
    _i5.SpeechLevel? level,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessions,
          [],
          {
            #userId: userId,
            #mode: mode,
            #level: level,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i2.GameSessionModel>>.value(
            <_i2.GameSessionModel>[]),
      ) as _i4.Future<List<_i2.GameSessionModel>>);

  @override
  _i4.Future<_i2.GameSessionModel> getSessionById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.GameSessionModel>.value(_FakeGameSessionModel_0(
          this,
          Invocation.method(
            #getSessionById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.GameSessionModel>);

  @override
  _i4.Future<List<_i2.GameSessionModel>> getPendingSessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSessions,
          [],
        ),
        returnValue: _i4.Future<List<_i2.GameSessionModel>>.value(
            <_i2.GameSessionModel>[]),
      ) as _i4.Future<List<_i2.GameSessionModel>>);

  @override
  _i4.Future<void> updateSessionSyncStatus(
    String? id,
    _i5.SyncStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSessionSyncStatus,
          [
            id,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSession(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSession,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cacheTags(List<_i6.TagModel>? tags) => (super.noSuchMethod(
        Invocation.method(
          #cacheTags,
          [tags],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.TagModel>> getCachedTags() => (super.noSuchMethod(
        Invocation.method(
          #getCachedTags,
          [],
        ),
        returnValue: _i4.Future<List<_i6.TagModel>>.value(<_i6.TagModel>[]),
      ) as _i4.Future<List<_i6.TagModel>>);

  @override
  _i4.Future<void> cacheSpeeches(List<_i7.SpeechModel>? speeches) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheSpeeches,
          [speeches],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.SpeechModel>> getCachedSpeeches({
    _i5.SpeechLevel? level,
    _i5.SpeechType? type,
    List<String>? tagIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedSpeeches,
          [],
          {
            #level: level,
            #type: type,
            #tagIds: tagIds,
          },
        ),
        returnValue:
            _i4.Future<List<_i7.SpeechModel>>.value(<_i7.SpeechModel>[]),
      ) as _i4.Future<List<_i7.SpeechModel>>);
}

/// A class which mocks [GameRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRemoteDataSource extends _i1.Mock
    implements _i8.GameRemoteDataSource {
  MockGameRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i6.TagModel>> getTags() => (super.noSuchMethod(
        Invocation.method(
          #getTags,
          [],
        ),
        returnValue: _i4.Future<List<_i6.TagModel>>.value(<_i6.TagModel>[]),
      ) as _i4.Future<List<_i6.TagModel>>);

  @override
  _i4.Future<List<_i7.SpeechModel>> getRandomSpeeches({
    required _i5.SpeechLevel? level,
    required _i5.SpeechType? type,
    List<String>? tagIds,
    int? count = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomSpeeches,
          [],
          {
            #level: level,
            #type: type,
            #tagIds: tagIds,
            #count: count,
          },
        ),
        returnValue:
            _i4.Future<List<_i7.SpeechModel>>.value(<_i7.SpeechModel>[]),
      ) as _i4.Future<List<_i7.SpeechModel>>);

  @override
  _i4.Future<String> createSession(_i2.GameSessionModel? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSession,
          [session],
        ),
        returnValue: _i4.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #createSession,
            [session],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<int> syncSessions(List<_i2.GameSessionModel>? sessions) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncSessions,
          [sessions],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i10.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i11.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i4.Stream<List<_i11.ConnectivityResult>>.empty(),
      ) as _i4.Stream<List<_i11.ConnectivityResult>>);

  @override
  _i4.Future<List<_i11.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i4.Future<List<_i11.ConnectivityResult>>.value(
            <_i11.ConnectivityResult>[]),
      ) as _i4.Future<List<_i11.ConnectivityResult>>);
}
