// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN2IynqzsUqIJ0cFUmA5Y0E7PBCzQdjzg',
    appId: '1:142566408634:web:33fb531481f083e01a1d83',
    messagingSenderId: '142566408634',
    projectId: 'haotran-enpratici',
    authDomain: 'haotran-enpratici.firebaseapp.com',
    storageBucket: 'haotran-enpratici.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN2IynqzsUqIJ0cFUmA5Y0E7PBCzQdjzg',
    appId: '1:142566408634:android:33fb531481f083e01a1d83',
    messagingSenderId: '142566408634',
    projectId: 'haotran-enpratici',
    storageBucket: 'haotran-enpratici.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN2IynqzsUqIJ0cFUmA5Y0E7PBCzQdjzg',
    appId: '1:142566408634:ios:33fb531481f083e01a1d83',
    messagingSenderId: '142566408634',
    projectId: 'haotran-enpratici',
    storageBucket: 'haotran-enpratici.firebasestorage.app',
    iosBundleId: 'vn.reetro.eng.app.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN2IynqzsUqIJ0cFUmA5Y0E7PBCzQdjzg',
    appId: '1:142566408634:ios:33fb531481f083e01a1d83',
    messagingSenderId: '142566408634',
    projectId: 'haotran-enpratici',
    storageBucket: 'haotran-enpratici.firebasestorage.app',
    iosBundleId: 'vn.reetro.eng.app.dev',
  );
}
