// Mocks generated by Mockito 5.4.4 from annotations
// in english_learning_app/test/unit/blocs/game_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i15;

import 'package:dartz/dartz.dart' as _i3;
import 'package:english_learning_app/core/constants/enums.dart' as _i10;
import 'package:english_learning_app/core/errors/failures.dart' as _i8;
import 'package:english_learning_app/data/datasources/local/audio_player_service.dart'
    as _i13;
import 'package:english_learning_app/data/datasources/local/audio_recorder_service.dart'
    as _i14;
import 'package:english_learning_app/data/datasources/remote/speech_remote_datasource.dart'
    as _i5;
import 'package:english_learning_app/domain/entities/game_session.dart' as _i12;
import 'package:english_learning_app/domain/entities/speech.dart' as _i9;
import 'package:english_learning_app/domain/repositories/game_repository.dart'
    as _i2;
import 'package:english_learning_app/domain/usecases/game/create_session_usecase.dart'
    as _i11;
import 'package:english_learning_app/domain/usecases/game/get_random_speeches_usecase.dart'
    as _i6;
import 'package:just_audio/just_audio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGameRepository_0 extends _i1.SmartFake
    implements _i2.GameRepository {
  _FakeGameRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioPlayer_2 extends _i1.SmartFake implements _i4.AudioPlayer {
  _FakeAudioPlayer_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_3 extends _i1.SmartFake implements Duration {
  _FakeDuration_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpeechScoreResponse_4 extends _i1.SmartFake
    implements _i5.SpeechScoreResponse {
  _FakeSpeechScoreResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetRandomSpeechesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRandomSpeechesUseCase extends _i1.Mock
    implements _i6.GetRandomSpeechesUseCase {
  MockGetRandomSpeechesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GameRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGameRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.GameRepository);

  @override
  _i7.Future<_i3.Either<_i8.Failure, List<_i9.Speech>>> call({
    required _i10.SpeechLevel? level,
    required _i10.SpeechType? type,
    List<String>? tagIds,
    int? count = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #level: level,
            #type: type,
            #tagIds: tagIds,
            #count: count,
          },
        ),
        returnValue:
            _i7.Future<_i3.Either<_i8.Failure, List<_i9.Speech>>>.value(
                _FakeEither_1<_i8.Failure, List<_i9.Speech>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #level: level,
              #type: type,
              #tagIds: tagIds,
              #count: count,
            },
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, List<_i9.Speech>>>);
}

/// A class which mocks [CreateSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateSessionUseCase extends _i1.Mock
    implements _i11.CreateSessionUseCase {
  MockCreateSessionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GameRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGameRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.GameRepository);

  @override
  _i7.Future<_i3.Either<_i8.Failure, _i12.GameSession>> call(
          _i12.GameSession? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [session],
        ),
        returnValue:
            _i7.Future<_i3.Either<_i8.Failure, _i12.GameSession>>.value(
                _FakeEither_1<_i8.Failure, _i12.GameSession>(
          this,
          Invocation.method(
            #call,
            [session],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, _i12.GameSession>>);
}

/// A class which mocks [AudioPlayerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayerService extends _i1.Mock
    implements _i13.AudioPlayerService {
  MockAudioPlayerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AudioPlayer get player => (super.noSuchMethod(
        Invocation.getter(#player),
        returnValue: _FakeAudioPlayer_2(
          this,
          Invocation.getter(#player),
        ),
      ) as _i4.AudioPlayer);

  @override
  Duration get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _FakeDuration_3(
          this,
          Invocation.getter(#position),
        ),
      ) as Duration);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  _i7.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i7.Stream<Duration>.empty(),
      ) as _i7.Stream<Duration>);

  @override
  _i7.Stream<_i4.PlayerState> get playerStateStream => (super.noSuchMethod(
        Invocation.getter(#playerStateStream),
        returnValue: _i7.Stream<_i4.PlayerState>.empty(),
      ) as _i7.Stream<_i4.PlayerState>);

  @override
  _i7.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i7.Stream<Duration?>.empty(),
      ) as _i7.Stream<Duration?>);

  @override
  _i7.Future<void> play(String? url) => (super.noSuchMethod(
        Invocation.method(
          #play,
          [url],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> replay() => (super.noSuchMethod(
        Invocation.method(
          #replay,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [AudioRecorderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioRecorderService extends _i1.Mock
    implements _i14.AudioRecorderService {
  MockAudioRecorderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> hasPermission() => (super.noSuchMethod(
        Invocation.method(
          #hasPermission,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> requestPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> startRecording() => (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i15.Uint8List> stopRecording() => (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i7.Future<_i15.Uint8List>.value(_i15.Uint8List(0)),
      ) as _i7.Future<_i15.Uint8List>);

  @override
  _i7.Future<void> cancelRecording() => (super.noSuchMethod(
        Invocation.method(
          #cancelRecording,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isRecording() => (super.noSuchMethod(
        Invocation.method(
          #isRecording,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  bool isBufferOverLimit() => (super.noSuchMethod(
        Invocation.method(
          #isBufferOverLimit,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> pauseRecording() => (super.noSuchMethod(
        Invocation.method(
          #pauseRecording,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> resumeRecording() => (super.noSuchMethod(
        Invocation.method(
          #resumeRecording,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [SpeechRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpeechRemoteDataSource extends _i1.Mock
    implements _i5.SpeechRemoteDataSource {
  MockSpeechRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.SpeechScoreResponse> scorePronunciation({
    required _i15.Uint8List? audioBytes,
    required String? referenceText,
    required String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scorePronunciation,
          [],
          {
            #audioBytes: audioBytes,
            #referenceText: referenceText,
            #language: language,
          },
        ),
        returnValue: _i7.Future<_i5.SpeechScoreResponse>.value(
            _FakeSpeechScoreResponse_4(
          this,
          Invocation.method(
            #scorePronunciation,
            [],
            {
              #audioBytes: audioBytes,
              #referenceText: referenceText,
              #language: language,
            },
          ),
        )),
      ) as _i7.Future<_i5.SpeechScoreResponse>);
}
