// Mocks generated by Mockito 5.4.4 from annotations
// in english_learning_app/test/unit/blocs/history_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:english_learning_app/core/constants/enums.dart' as _i8;
import 'package:english_learning_app/core/errors/failures.dart' as _i6;
import 'package:english_learning_app/domain/entities/game_session.dart' as _i7;
import 'package:english_learning_app/domain/repositories/game_repository.dart'
    as _i2;
import 'package:english_learning_app/domain/usecases/game/get_sessions_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGameRepository_0 extends _i1.SmartFake
    implements _i2.GameRepository {
  _FakeGameRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetSessionsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSessionsUseCase extends _i1.Mock
    implements _i4.GetSessionsUseCase {
  MockGetSessionsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GameRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGameRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.GameRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.GameSession>>> call({
    _i8.GameMode? mode,
    _i8.SpeechLevel? level,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #mode: mode,
            #level: level,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.GameSession>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.GameSession>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #mode: mode,
              #level: level,
              #startDate: startDate,
              #endDate: endDate,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.GameSession>>>);
}
